baseURL = 'https://thezelus.github.io'
languageCode = 'en-us'
title = "The Loonie Bin"
theme = 'holy'


[params]
  copyright = "Â© Abhishek Sharma"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
   tag = "tags"